//------------------------------------------------------------------------------
// <auto-generated>
//     Hand-maintained strongly-typed accessor for HellionStrings.resx.
//     Mirrors the layout of Language.Designer.cs so the same Plugin.cs
//     LanguageChanged handler can update Culture for both classes.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace HellionChat.Resources;

[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
internal class HellionStrings
{
    private static global::System.Resources.ResourceManager? resourceMan;
    private static global::System.Globalization.CultureInfo? resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal HellionStrings() { }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (resourceMan is null)
                resourceMan = new global::System.Resources.ResourceManager("HellionChat.Resources.HellionStrings", typeof(HellionStrings).Assembly);
            return resourceMan;
        }
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    private static string Get(string key)
        => ResourceManager.GetString(key, resourceCulture) ?? key;

    internal static string Privacy_Tab_Title => Get(nameof(Privacy_Tab_Title));
    internal static string Privacy_FilterEnabled_Name => Get(nameof(Privacy_FilterEnabled_Name));
    internal static string Privacy_FilterEnabled_Description => Get(nameof(Privacy_FilterEnabled_Description));
    internal static string Privacy_FilterEnabled_StorageOnly_Help => Get(nameof(Privacy_FilterEnabled_StorageOnly_Help));
    internal static string Privacy_Filter_Tree_Heading => Get(nameof(Privacy_Filter_Tree_Heading));
    internal static string Privacy_Whitelist_Help => Get(nameof(Privacy_Whitelist_Help));
    internal static string Privacy_Preset_PrivacyFirst => Get(nameof(Privacy_Preset_PrivacyFirst));
    internal static string Privacy_Preset_ClearAll => Get(nameof(Privacy_Preset_ClearAll));
    internal static string Privacy_Preset_SelectAll => Get(nameof(Privacy_Preset_SelectAll));
    internal static string Privacy_Group_DirectMessages => Get(nameof(Privacy_Group_DirectMessages));
    internal static string Privacy_Group_PartyAlliance => Get(nameof(Privacy_Group_PartyAlliance));
    internal static string Privacy_Group_FreeCompany => Get(nameof(Privacy_Group_FreeCompany));
    internal static string Privacy_Group_Linkshells => Get(nameof(Privacy_Group_Linkshells));
    internal static string Privacy_Group_CrossLinkshells => Get(nameof(Privacy_Group_CrossLinkshells));
    internal static string Privacy_Group_ExtraChat => Get(nameof(Privacy_Group_ExtraChat));
    internal static string Privacy_Group_PublicChat => Get(nameof(Privacy_Group_PublicChat));
    internal static string Privacy_Group_SystemLogs => Get(nameof(Privacy_Group_SystemLogs));
    internal static string Privacy_PersistUnknown_Name => Get(nameof(Privacy_PersistUnknown_Name));
    internal static string Privacy_PersistUnknown_Description => Get(nameof(Privacy_PersistUnknown_Description));

    internal static string Cleanup_Heading => Get(nameof(Cleanup_Heading));
    internal static string Cleanup_Help_Intro => Get(nameof(Cleanup_Help_Intro));
    internal static string Cleanup_Help_SavedNote => Get(nameof(Cleanup_Help_SavedNote));
    internal static string Cleanup_Preview_Stale => Get(nameof(Cleanup_Preview_Stale));
    internal static string Retention_Help_SavedNote => Get(nameof(Retention_Help_SavedNote));
    internal static string Cleanup_RefreshPreview => Get(nameof(Cleanup_RefreshPreview));
    internal static string Cleanup_NoPreview => Get(nameof(Cleanup_NoPreview));
    internal static string Cleanup_TotalStored => Get(nameof(Cleanup_TotalStored));
    internal static string Cleanup_WillKeep => Get(nameof(Cleanup_WillKeep));
    internal static string Cleanup_WillDelete => Get(nameof(Cleanup_WillDelete));
    internal static string Cleanup_Breakdown => Get(nameof(Cleanup_Breakdown));
    internal static string Cleanup_Marker_Keep => Get(nameof(Cleanup_Marker_Keep));
    internal static string Cleanup_Marker_Delete => Get(nameof(Cleanup_Marker_Delete));
    internal static string Cleanup_Apply_Label => Get(nameof(Cleanup_Apply_Label));
    internal static string Cleanup_Apply_Tooltip => Get(nameof(Cleanup_Apply_Tooltip));
    internal static string Cleanup_Running => Get(nameof(Cleanup_Running));
    internal static string Cleanup_PreviewError => Get(nameof(Cleanup_PreviewError));
    internal static string Cleanup_Success => Get(nameof(Cleanup_Success));
    internal static string Cleanup_Error => Get(nameof(Cleanup_Error));

    internal static string Retention_Heading => Get(nameof(Retention_Heading));
    internal static string Retention_Enabled_Name => Get(nameof(Retention_Enabled_Name));
    internal static string Retention_Enabled_Description => Get(nameof(Retention_Enabled_Description));
    internal static string Retention_Default_Label => Get(nameof(Retention_Default_Label));
    internal static string Retention_Default_Help => Get(nameof(Retention_Default_Help));
    internal static string Retention_Reset_Spec => Get(nameof(Retention_Reset_Spec));
    internal static string Retention_Clear_Overrides => Get(nameof(Retention_Clear_Overrides));
    internal static string Retention_Tree_Heading => Get(nameof(Retention_Tree_Heading));
    internal static string Retention_Tag_Override => Get(nameof(Retention_Tag_Override));
    internal static string Retention_Tag_Spec => Get(nameof(Retention_Tag_Spec));
    internal static string Retention_Tag_Global => Get(nameof(Retention_Tag_Global));
    internal static string Retention_Reset_Button => Get(nameof(Retention_Reset_Button));
    internal static string Retention_Apply_Label => Get(nameof(Retention_Apply_Label));
    internal static string Retention_Apply_Tooltip => Get(nameof(Retention_Apply_Tooltip));
    internal static string Retention_Running => Get(nameof(Retention_Running));
    internal static string Retention_LastRun_Never => Get(nameof(Retention_LastRun_Never));
    internal static string Retention_LastRun_At => Get(nameof(Retention_LastRun_At));
    internal static string Retention_Success => Get(nameof(Retention_Success));
    internal static string Retention_Error => Get(nameof(Retention_Error));

    internal static string Wizard_Title => Get(nameof(Wizard_Title));
    internal static string Wizard_Intro => Get(nameof(Wizard_Intro));
    internal static string Wizard_Profile_PrivacyFirst_Heading => Get(nameof(Wizard_Profile_PrivacyFirst_Heading));
    internal static string Wizard_Profile_PrivacyFirst_Description => Get(nameof(Wizard_Profile_PrivacyFirst_Description));
    internal static string Wizard_Profile_PrivacyFirst_Apply => Get(nameof(Wizard_Profile_PrivacyFirst_Apply));
    internal static string Wizard_Profile_Casual_Heading => Get(nameof(Wizard_Profile_Casual_Heading));
    internal static string Wizard_Profile_Casual_Description => Get(nameof(Wizard_Profile_Casual_Description));
    internal static string Wizard_Profile_Casual_Apply => Get(nameof(Wizard_Profile_Casual_Apply));
    internal static string Wizard_Profile_FullHistory_Heading => Get(nameof(Wizard_Profile_FullHistory_Heading));
    internal static string Wizard_Profile_FullHistory_Description => Get(nameof(Wizard_Profile_FullHistory_Description));
    internal static string Wizard_Profile_FullHistory_GdprWarning => Get(nameof(Wizard_Profile_FullHistory_GdprWarning));
    internal static string Wizard_Profile_FullHistory_Apply => Get(nameof(Wizard_Profile_FullHistory_Apply));
    internal static string Wizard_Reopen_Button => Get(nameof(Wizard_Reopen_Button));

    internal static string Export_Heading => Get(nameof(Export_Heading));
    internal static string Export_Help => Get(nameof(Export_Help));
    internal static string Export_Range_Label => Get(nameof(Export_Range_Label));
    internal static string Export_Sender_Label => Get(nameof(Export_Sender_Label));
    internal static string Export_Channels_Heading => Get(nameof(Export_Channels_Heading));
    internal static string Export_Channels_AllOff => Get(nameof(Export_Channels_AllOff));
    internal static string Export_Format_Label => Get(nameof(Export_Format_Label));
    internal static string Export_Format_Markdown => Get(nameof(Export_Format_Markdown));
    internal static string Export_Format_Json => Get(nameof(Export_Format_Json));
    internal static string Export_Format_Csv => Get(nameof(Export_Format_Csv));
    internal static string Export_Button => Get(nameof(Export_Button));
    internal static string Export_Dialog_Title => Get(nameof(Export_Dialog_Title));
    internal static string Export_Running => Get(nameof(Export_Running));
    internal static string Export_Success => Get(nameof(Export_Success));
    internal static string Export_Empty => Get(nameof(Export_Empty));
    internal static string Export_Error => Get(nameof(Export_Error));

    internal static string Theme_Enabled_Name => Get(nameof(Theme_Enabled_Name));
    internal static string Theme_Enabled_Description => Get(nameof(Theme_Enabled_Description));
    internal static string Theme_WindowOpacity_Label => Get(nameof(Theme_WindowOpacity_Label));
    internal static string Theme_WindowOpacity_Help => Get(nameof(Theme_WindowOpacity_Help));
    internal static string Theme_UseHellionFont_Name => Get(nameof(Theme_UseHellionFont_Name));
    internal static string Theme_UseHellionFont_Description => Get(nameof(Theme_UseHellionFont_Description));

    internal static string About_Maintainer_Heading => Get(nameof(About_Maintainer_Heading));
    internal static string About_Maintainer_Body => Get(nameof(About_Maintainer_Body));
    internal static string About_Maintainer_Website_Label => Get(nameof(About_Maintainer_Website_Label));
    internal static string About_Mission_Heading => Get(nameof(About_Mission_Heading));
    internal static string About_Mission_P1 => Get(nameof(About_Mission_P1));
    internal static string About_Mission_P2 => Get(nameof(About_Mission_P2));
    internal static string About_Mission_P3 => Get(nameof(About_Mission_P3));
    internal static string About_BuiltOn_Heading => Get(nameof(About_BuiltOn_Heading));
    internal static string About_BuiltOn_P1 => Get(nameof(About_BuiltOn_P1));
    internal static string About_BuiltOn_P2 => Get(nameof(About_BuiltOn_P2));
    internal static string About_BuiltOn_Upstream_Label => Get(nameof(About_BuiltOn_Upstream_Label));
    internal static string About_License_Heading => Get(nameof(About_License_Heading));
    internal static string About_License_P1 => Get(nameof(About_License_P1));
    internal static string About_License_P2 => Get(nameof(About_License_P2));
    internal static string About_License_P3 => Get(nameof(About_License_P3));
    internal static string About_SE_Heading => Get(nameof(About_SE_Heading));
    internal static string About_SE_P1 => Get(nameof(About_SE_P1));
    internal static string About_SE_P2 => Get(nameof(About_SE_P2));
    internal static string About_Localization_Heading => Get(nameof(About_Localization_Heading));
    internal static string About_Localization_P1 => Get(nameof(About_Localization_P1));
    internal static string About_Localization_P2 => Get(nameof(About_Localization_P2));
    internal static string About_Translators_TreeNode => Get(nameof(About_Translators_TreeNode));

    // Hellion Chat — Auto-Tell-Tabs runtime strings
    internal static string AutoTellTabs_SectionHeader => Get(nameof(AutoTellTabs_SectionHeader));
    internal static string AutoTellTabs_HistorySeparator => Get(nameof(AutoTellTabs_HistorySeparator));
    internal static string AutoTellTabs_HistoryLoadError => Get(nameof(AutoTellTabs_HistoryLoadError));
    internal static string AutoTellTabs_GreetedTooltip => Get(nameof(AutoTellTabs_GreetedTooltip));
    internal static string AutoTellTabs_UnGreetedTooltip => Get(nameof(AutoTellTabs_UnGreetedTooltip));

    // Hellion Chat — Auto-Tell-Tabs Chat settings tab
    internal static string ChatLog_AutoTellTabs_Section_Title => Get(nameof(ChatLog_AutoTellTabs_Section_Title));
    internal static string ChatLog_AutoTellTabs_Enable_Name => Get(nameof(ChatLog_AutoTellTabs_Enable_Name));
    internal static string ChatLog_AutoTellTabs_Enable_Description => Get(nameof(ChatLog_AutoTellTabs_Enable_Description));
    internal static string ChatLog_AutoTellTabs_Limit_Name => Get(nameof(ChatLog_AutoTellTabs_Limit_Name));
    internal static string ChatLog_AutoTellTabs_Limit_Description => Get(nameof(ChatLog_AutoTellTabs_Limit_Description));
    internal static string ChatLog_AutoTellTabs_Compact_Name => Get(nameof(ChatLog_AutoTellTabs_Compact_Name));
    internal static string ChatLog_AutoTellTabs_Compact_Description => Get(nameof(ChatLog_AutoTellTabs_Compact_Description));
    internal static string ChatLog_AutoTellTabs_GreetedToggle_Name => Get(nameof(ChatLog_AutoTellTabs_GreetedToggle_Name));
    internal static string ChatLog_AutoTellTabs_GreetedToggle_Description => Get(nameof(ChatLog_AutoTellTabs_GreetedToggle_Description));
    internal static string ChatLog_AutoTellTabs_OpenAsPopout_Name => Get(nameof(ChatLog_AutoTellTabs_OpenAsPopout_Name));
    internal static string ChatLog_AutoTellTabs_OpenAsPopout_Description => Get(nameof(ChatLog_AutoTellTabs_OpenAsPopout_Description));
    internal static string ChatLog_AutoTellTabs_PreloadHint => Get(nameof(ChatLog_AutoTellTabs_PreloadHint));
    internal static string ChatLog_AutoTellTabs_ConflictHint => Get(nameof(ChatLog_AutoTellTabs_ConflictHint));

    // Hellion Chat — Auto-Tell-Tabs Privacy settings tab
    internal static string Privacy_AutoTellTabs_Section_Title => Get(nameof(Privacy_AutoTellTabs_Section_Title));
    internal static string Privacy_AutoTellTabs_Preload_Name => Get(nameof(Privacy_AutoTellTabs_Preload_Name));
    internal static string Privacy_AutoTellTabs_Preload_Description => Get(nameof(Privacy_AutoTellTabs_Preload_Description));
    internal static string Privacy_AutoTellTabs_Preload_Hint => Get(nameof(Privacy_AutoTellTabs_Preload_Hint));

    // Hellion Chat — Settings UX Polish v10 wipe migration
    internal static string SettingsRefactor_Migration_Title => Get(nameof(SettingsRefactor_Migration_Title));
    internal static string SettingsRefactor_Migration_Content => Get(nameof(SettingsRefactor_Migration_Content));

    // Hellion Chat — Settings UX Polish 8-tab structure
    internal static string Settings_Tab_General => Get(nameof(Settings_Tab_General));
    internal static string Settings_Tab_Appearance => Get(nameof(Settings_Tab_Appearance));
    internal static string Settings_Tab_Window => Get(nameof(Settings_Tab_Window));
    internal static string Settings_Tab_Chat => Get(nameof(Settings_Tab_Chat));
    internal static string Settings_Tab_Tabs => Get(nameof(Settings_Tab_Tabs));
    internal static string Settings_Tab_Database => Get(nameof(Settings_Tab_Database));
    internal static string Settings_Tab_Information => Get(nameof(Settings_Tab_Information));

    // v1.1.0 — Settings card-grid overview
    internal static string Settings_Card_General_Title => Get(nameof(Settings_Card_General_Title));
    internal static string Settings_Card_General_Subtext => Get(nameof(Settings_Card_General_Subtext));
    internal static string Settings_Card_Appearance_Title => Get(nameof(Settings_Card_Appearance_Title));
    internal static string Settings_Card_Appearance_Subtext => Get(nameof(Settings_Card_Appearance_Subtext));
    internal static string Settings_Card_Themes_Title => Get(nameof(Settings_Card_Themes_Title));
    internal static string Settings_Card_Themes_Subtext => Get(nameof(Settings_Card_Themes_Subtext));
    internal static string Settings_Card_Window_Title => Get(nameof(Settings_Card_Window_Title));
    internal static string Settings_Card_Window_Subtext => Get(nameof(Settings_Card_Window_Subtext));
    internal static string Settings_Card_Chat_Title => Get(nameof(Settings_Card_Chat_Title));
    internal static string Settings_Card_Chat_Subtext => Get(nameof(Settings_Card_Chat_Subtext));
    internal static string Settings_Card_Tabs_Title => Get(nameof(Settings_Card_Tabs_Title));
    internal static string Settings_Card_Tabs_Subtext => Get(nameof(Settings_Card_Tabs_Subtext));
    internal static string Settings_Card_Privacy_Title => Get(nameof(Settings_Card_Privacy_Title));
    internal static string Settings_Card_Privacy_Subtext => Get(nameof(Settings_Card_Privacy_Subtext));
    internal static string Settings_Card_Database_Title => Get(nameof(Settings_Card_Database_Title));
    internal static string Settings_Card_Database_Subtext => Get(nameof(Settings_Card_Database_Subtext));
    internal static string Settings_Card_Information_Title => Get(nameof(Settings_Card_Information_Title));
    internal static string Settings_Card_Information_Subtext => Get(nameof(Settings_Card_Information_Subtext));

    // v1.1.0 — Themes-Settings-Tab
    internal static string Settings_Tab_Themes => Get(nameof(Settings_Tab_Themes));
    internal static string Settings_Themes_Active => Get(nameof(Settings_Themes_Active));
    internal static string Settings_Themes_BuiltIns => Get(nameof(Settings_Themes_BuiltIns));
    internal static string Settings_Themes_Custom => Get(nameof(Settings_Themes_Custom));
    internal static string Settings_Themes_OpenFolder => Get(nameof(Settings_Themes_OpenFolder));
    internal static string Settings_Themes_ExportActive => Get(nameof(Settings_Themes_ExportActive));
    internal static string Settings_Themes_ApplyChatColors_Hint => Get(nameof(Settings_Themes_ApplyChatColors_Hint));
    internal static string Settings_Themes_ApplyChatColors_Apply => Get(nameof(Settings_Themes_ApplyChatColors_Apply));
    internal static string Settings_Themes_ApplyChatColors_Keep => Get(nameof(Settings_Themes_ApplyChatColors_Keep));

    // Hellion Chat — General-Tab section headings
    internal static string Settings_General_Input_Heading => Get(nameof(Settings_General_Input_Heading));
    internal static string Settings_General_Audio_Heading => Get(nameof(Settings_General_Audio_Heading));
    internal static string Settings_General_Performance_Heading => Get(nameof(Settings_General_Performance_Heading));
    internal static string Settings_General_Language_Heading => Get(nameof(Settings_General_Language_Heading));

    // Hellion Chat — Appearance-Tab section headings
    internal static string Settings_Appearance_Theme_Heading => Get(nameof(Settings_Appearance_Theme_Heading));
    internal static string Settings_Appearance_Fonts_Heading => Get(nameof(Settings_Appearance_Fonts_Heading));
    internal static string Settings_Appearance_Colours_Heading => Get(nameof(Settings_Appearance_Colours_Heading));
    internal static string Settings_Appearance_Timestamps_Heading => Get(nameof(Settings_Appearance_Timestamps_Heading));

    // Hellion Chat — Window-Tab section headings
    internal static string Settings_Window_Hide_Heading => Get(nameof(Settings_Window_Hide_Heading));
    internal static string Settings_Window_InactivityHide_Heading => Get(nameof(Settings_Window_InactivityHide_Heading));
    internal static string Settings_Window_Frame_Heading => Get(nameof(Settings_Window_Frame_Heading));
    internal static string Settings_Window_Tooltips_Heading => Get(nameof(Settings_Window_Tooltips_Heading));

    // Hellion Chat — Chat-Tab section headings
    internal static string Settings_Chat_AutoTellTabs_Heading => Get(nameof(Settings_Chat_AutoTellTabs_Heading));
    internal static string Settings_Chat_Behaviour_Heading => Get(nameof(Settings_Chat_Behaviour_Heading));
    internal static string Settings_Chat_Preview_Heading => Get(nameof(Settings_Chat_Preview_Heading));
    internal static string Settings_Chat_Emotes_Heading => Get(nameof(Settings_Chat_Emotes_Heading));

    // Hellion Chat — Database-Tab section headings
    internal static string Settings_Database_Storage_Heading => Get(nameof(Settings_Database_Storage_Heading));
    internal static string Settings_Database_Viewer_Heading => Get(nameof(Settings_Database_Viewer_Heading));
    internal static string Settings_Database_Stats_Heading => Get(nameof(Settings_Database_Stats_Heading));

    // Hellion Chat — Information-Tab section headings
    internal static string Settings_Information_VersionInfo_Heading => Get(nameof(Settings_Information_VersionInfo_Heading));
    internal static string Settings_Information_About_Heading => Get(nameof(Settings_Information_About_Heading));
    internal static string Settings_Information_Changelog_Heading => Get(nameof(Settings_Information_Changelog_Heading));

    // Hellion Chat — Default tab presets (channel-themed)
    internal static string Tabs_Presets_System => Get(nameof(Tabs_Presets_System));
    internal static string Tabs_Presets_FreeCompany => Get(nameof(Tabs_Presets_FreeCompany));
    internal static string Tabs_Presets_Party => Get(nameof(Tabs_Presets_Party));
    internal static string Tabs_Presets_Beginner => Get(nameof(Tabs_Presets_Beginner));
    internal static string Tabs_Presets_Linkshell => Get(nameof(Tabs_Presets_Linkshell));
    internal static string Tabs_Presets_Linkshell_Hint => Get(nameof(Tabs_Presets_Linkshell_Hint));

    // Hellion Chat — v1.2.0 per-tab icon override
    internal static string Tabs_Icon_Label => Get(nameof(Tabs_Icon_Label));
    internal static string Tabs_Icon_HelpMarker => Get(nameof(Tabs_Icon_HelpMarker));
    internal static string Tabs_Icon_DefaultOption => Get(nameof(Tabs_Icon_DefaultOption));

    // Hellion Chat — v0.6.0 chat colour presets (display labels)
    internal static string ChatColourPresets_Default => Get(nameof(ChatColourPresets_Default));
    internal static string ChatColourPresets_HighContrast => Get(nameof(ChatColourPresets_HighContrast));
    internal static string ChatColourPresets_Pastell => Get(nameof(ChatColourPresets_Pastell));
    internal static string ChatColourPresets_DarkModeTuned => Get(nameof(ChatColourPresets_DarkModeTuned));
    internal static string ChatColourPresets_Hellion => Get(nameof(ChatColourPresets_Hellion));
    internal static string ChatColourPresets_NightBlue => Get(nameof(ChatColourPresets_NightBlue));
    internal static string ChatColourPresets_IndigoViolet => Get(nameof(ChatColourPresets_IndigoViolet));

    // Hellion Chat — v0.6.0 chat colour presets section copy
    internal static string Settings_Appearance_Colours_PresetsHint => Get(nameof(Settings_Appearance_Colours_PresetsHint));

    // Hellion Chat — v0.6.0 pop-out input master switch
    internal static string Settings_Window_PopOutInputEnabled_Name => Get(nameof(Settings_Window_PopOutInputEnabled_Name));
    internal static string Settings_Window_PopOutInputEnabled_Description => Get(nameof(Settings_Window_PopOutInputEnabled_Description));

    // Hellion Chat — Window position recovery (off-screen safety net)
    internal static string Settings_Window_ResetPosition_Name => Get(nameof(Settings_Window_ResetPosition_Name));
    internal static string Settings_Window_ResetPosition_Description => Get(nameof(Settings_Window_ResetPosition_Description));

    // Hellion Chat — v0.6.0 one-time hint banner shown inside pop-outs
    internal static string Popout_v060_HintText => Get(nameof(Popout_v060_HintText));
    internal static string Popout_v060_HintAck => Get(nameof(Popout_v060_HintAck));
    internal static string Popout_v060_HintOpenSettings => Get(nameof(Popout_v060_HintOpenSettings));

    // Hellion Chat — v0.6.1 pop-out header hint banner (discoverability)
    internal static string Hint_v061_PopOutHeader_Body => Get(nameof(Hint_v061_PopOutHeader_Body));
    internal static string Hint_v061_PopOutHeader_Ack => Get(nameof(Hint_v061_PopOutHeader_Ack));
    internal static string Hint_v061_PopOutHeader_OpenSettings => Get(nameof(Hint_v061_PopOutHeader_OpenSettings));

    // Hellion Chat — v1.0.0 Chat 2 parallel-load conflict detection
    internal static string ChatTwoConflictTitle => Get(nameof(ChatTwoConflictTitle));
    internal static string ChatTwoConflictBody => Get(nameof(ChatTwoConflictBody));
    internal static string ChatTwoConflictAction => Get(nameof(ChatTwoConflictAction));

    // Hellion Chat — v1.2.0 Bottom-Status-Bar Privacy-Badge labels
    internal static string StatusBar_Privacy_Enabled => Get(nameof(StatusBar_Privacy_Enabled));
    internal static string StatusBar_Privacy_Open => Get(nameof(StatusBar_Privacy_Open));
}
